### ISSUE TITLE
Add opengraph metadata to posts for higher quality social sharing

### ISSUE THREAD

**Issue by kpetku** [majestrate/i2p.rocks.blog#17]
Hi i2p.rocks people,

I just happen to share your blog content quite frequently on Facebook.  The posts shared there look really plain.  Would you oppose adding an `og:image` tag as suggested [here](http://docs.getpelican.com/en/3.6.3/themes.html#article-html) like
```<meta` property="og:image" content="{{ article.facebookimage }}"/>``` and/or provide a default logo that would show up via [opengraph](http://ogp.me/) metadata?

Perhaps you could use something like this (_shamelessly_ ripped from the summer of i2p campaign):
![i2procks-fb](https://cloud.githubusercontent.com/assets/2693010/22858793/9324e68e-f095-11e6-8d4d-643641e976ac.png)

Please let me know what you think, or close this issue out if you don't feel like it's a priority.

**Comment by majestrate** [comment]
I have never heard of this convention as I am not a web person, will add this ASAP as that logo is super rad.

**Comment by majestrate** [comment]
should be deployed now, let me know if that is broken or not.

**Comment by kpetku** [comment]
Hi again,

Yeah, OGP is a cause for a lot of frustration in the content sharing world.  I checked a recent article with fb's [debugger](https://developers.facebook.com/tools/debug/sharing/) and the result was:
![kpetku-2017-02-11-21-54-42](https://cloud.githubusercontent.com/assets/2693010/22859293/c7b1c08e-f0a4-11e6-82a6-4e5669d5a337.png)
I think it requires an absolute URI.  Ditto for the ```og:url```, as this [stackoverflow](http://stackoverflow.com/questions/9038025/facebook-object-debugger-property-ogurl-could-not-be-parsed-as-type-url) article suggests.

I'm not sure if the debugger is going to complain about a lack of ```og:image:secure_url``` or not.

**Comment by majestrate** [comment]
alrighty i think i got it those og urls to be absolute now, let me know.

**Comment by kpetku** [comment]
Okay, it renders the logo now, but FB auto crops it and incorrectly cuts the edges off.  This one should work better:
![og-logo2](https://cloud.githubusercontent.com/assets/2693010/22863433/e93015ee-f10d-11e6-87ae-686341cfdab2.png)

The results can be checked without FB using this checker:
https://realfavicongenerator.net/social/checker

**Comment by majestrate** [comment]
thanks for useful link, will use in future.

**Comment by kpetku** [comment]
It looks good now, closing, thanks!
